=== trebent/kerberos/internal/config/schemas/config_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://trebent.com/kerberos/schemas/config_schema.json",
  "type": "object",
  "description": "Kerberos API gateway configuration.",
  "properties": {
    "gateway": {
      "$ref": "http://trebent.com/kerberos/schemas/gateway_schema.json"
    },
    "oas": {
      "$ref": "http://trebent.com/kerberos/schemas/oas_schema.json"
    },
    "auth": {
      "$ref": "http://trebent.com/kerberos/schemas/auth_schema.json"
    },
    "admin": {
      "$ref": "http://trebent.com/kerberos/schemas/admin_schema.json"
    },
    "observability": {
      "$ref": "http://trebent.com/kerberos/schemas/observability_schema.json"
    },
    "persistence": {
      "$ref": "http://trebent.com/kerberos/schemas/persistence_schema.json"
    }
  },
  "additionalProperties": false,
  "required": [
    "gateway"
  ]
}

=== trebent/kerberos/test/suites/krbctl/testdata/config/krb.json
{
  "auth": {
    "methods": {
      "basic": {}
    },
    "order": 1,
    "scheme": {
      "mappings": [
        {
          "backend": "api",
          "exempt": [],
          "method": "basic"
        }
      ]
    }
  },
  "gateway": {
    "router": {
      "backends": [
        {
          "host": "echo",
          "name": "echo",
          "port": 15000
        },
        {
          "host": "api",
          "name": "api",
          "port": 8080
        }
      ]
    }
  },
  "observability": {
    "enabled": true,
    "runtimeMetrics": true
  },
  "persistence": {
    "address": "postgres:5432",
    "driver": "postgres",
    "postgres": {
      "database": "kerberos",
      "password": "kerberos",
      "sslMode": "disable",
      "username": "kerberos"
    }
  }
}

=== trebent/kerberos/test/config/integration.json
{
  "admin": {
    "api": {
      "origins": {
        "allowAll": true
      }
    }
  },
  "persistence": {
    "driver": "postgres",
    "address": "postgres:5432",
    "postgres": {
      "database": "kerberos",
      "username": "kerberos",
      "password": "kerberos",
      "sslMode": "disable"
    }
  },
  "gateway": {
    "router": {
      "backends": [
        {
          "name": "echo",
          "host": "echo",
          "port": 15000
        },
        {
          "name": "protected-echo",
          "host": "protected-echo",
          "port": 15000
        }
      ]
    }
  },
  "auth": {
    "methods": {
      "basic": {
        "api": {
          "origins": {
            "allowAll": true
          }
        }
      }
    },
    "scheme": {
      "mappings": [
        {
          "backend": "${ref:gateway.router.backends[1].name}",
          "method": "basic",
          "exempt": [
            "/unprotected",
            "/unprotected/*"
          ],
          "authorization": {
            "groups": [
              "staff"
            ],
            "paths": {
              "/long/hello": [
                "pleb"
              ]
            }
          }
        }
      ]
    },
    "order": 1
  },
  "oas": {
    "mappings": [
      {
        "backend": "${ref:gateway.router.backends[0].name}",
        "specification": "/oas/echo.yaml"
      },
      {
        "backend": "${ref:gateway.router.backends[1].name}",
        "specification": "/oas/echo-protected.yaml"
      }
    ],
    "order": 100
  }
}

=== trebent/kerberos/test/compose/staging/krb.json
{
  "admin": {
    "api": {
      "cookies": {
        "domain": "trebent.test",
        "sameSite": "Strict"
      },
      "origins": {
        "allowedOrigins": [
          "https://trebent.test:4200"
        ]
      },
      "tls": {
        "serverCertFile": "/certs/krb.pem",
        "serverKeyFile": "/certs/krb-key.pem"
      }
    }
  },
  "persistence": {
    "driver": "postgres",
    "address": "postgres:5432",
    "postgres": {
      "database": "kerberos",
      "username": "kerberos",
      "password": "kerberos",
      "sslMode": "disable"
    }
  },
  "gateway": {
    "tls": {
      "serverCertFile": "/certs/krb.pem",
      "serverKeyFile": "/certs/krb-key.pem"
    },
    "router": {
      "backends": [
        {
          "name": "echo",
          "host": "echo",
          "port": 15000,
          "origins": {
            "allowAll": true
          }
        },
        {
          "name": "protected-echo",
          "host": "protected-echo",
          "port": 15000,
          "origins": {
            "denyAll": true
          }
        }
      ]
    }
  },
  "auth": {
    "methods": {
      "basic": {
        "api": {
          "origins": {
            "allowAll": true
          }
        }
      }
    },
    "scheme": {
      "mappings": [
        {
          "backend": "${ref:gateway.router.backends[1].name}",
          "method": "basic",
          "exempt": [
            "/unprotected",
            "/unprotected/*"
          ],
          "authorization": {
            "groups": [
              "staff"
            ],
            "paths": {
              "/long/hello": [
                "pleb"
              ]
            }
          }
        }
      ]
    },
    "order": 1
  },
  "oas": {
    "mappings": [
      {
        "backend": "${ref:gateway.router.backends[0].name}",
        "specification": "/oas/echo.yaml"
      },
      {
        "backend": "${ref:gateway.router.backends[1].name}",
        "specification": "/oas/echo-protected.yaml"
      }
    ],
    "order": 100
  }
}

=== trebent/kerberos/poc/poc.json
{
  "persistence": {
    "driver": "sqlite",
    "address": "krb.db"
  },
  "gateway": {
    "router": {
      "backends": [
        {
          "name": "echo",
          "host": "localhost",
          "port": 15000
        }
      ]
    }
  },
  "auth": {
    "methods": {
      "basic": {}
    },
    "scheme": {
      "mappings": [
        {
          "backend": "${ref:gateway.router.backends[0].name}",
          "method": "basic"
        }
      ]
    },
    "order": 1
  },
  "observability": {
    "enabled": false
  }
}

=== trebent/kerberos/test/config/security.json
{
  "admin": {
    "api": {
      "cookies": {
        "domain": "krbtest.com",
        "sameSite": "Lax"
      },
      "origins": {
        "allowedOrigins": [
          "http://www.safe.com"
        ]
      },
      "tls": {
        "serverCertFile": "/certs/krb_server.pem",
        "serverKeyFile": "/certs/krb_server.key"
      }
    }
  },
  "observability": {
    "enabled": false
  },
  "auth": {
    "methods": {
      "basic": {
        "api": {
          "cookies": {
            "domain": "otherkrbtest.com",
            "sameSite": "Strict"
          },
          "origins": {
            "denyAll": true
          }
        }
      }
    },
    "scheme": {
      "mappings": [
        {
          "backend": "dummy",
          "method": "basic"
        }
      ]
    }
  },
  "gateway": {
    "tls": {
      "serverCertFile": "/certs/krb_server.pem",
      "serverKeyFile": "/certs/krb_server.key"
    },
    "router": {
      "backends": [
        {
          "name": "mtls-echo",
          "host": "mtls-echo",
          "port": 15000,
          "origins": {
            "denyAll": true
          },
          "tls": {
            "rootCAFile": "/certs/ca.crt",
            "clientCertFile": "/certs/krb_client.pem",
            "clientKeyFile": "/certs/krb_client.key",
            "insecureSkipVerify": false
          }
        },
        {
          "name": "tls-echo",
          "host": "tls-echo",
          "port": 15000,
          "origins": {
            "allowedOrigins": [
              "http://www.safe.com"
            ]
          },
          "tls": {
            "rootCAFile": "/certs/ca.crt",
            "insecureSkipVerify": false
          }
        },
        {
          "name": "dummy",
          "host": "dummy",
          "port": 12345
        }
      ]
    }
  },
  "oas": {
    "mappings": [
      {
        "backend": "${ref:gateway.router.backends[0].name}",
        "specification": "/oas/echo.yaml"
      }
    ],
    "order": 100
  }
}

=== trebent/kerberos/test/config/docker.json
{
  "persistence": {
    "driver": "sqlite",
    "address": "krb.db"
  },
  "gateway": {
    "router": {
      "backends": [
        {
          "name": "echo",
          "host": "echo",
          "port": 15000
        }
      ]
    }
  },
  "auth": {
    "methods": {
      "basic": {}
    },
    "scheme": {
      "mappings": [
        {
          "backend": "${ref:gateway.router.backends[0].name}",
          "method": "basic"
        }
      ]
    },
    "order": 1
  },
  "observability": {
    "enabled": false
  },
  "oas": {
    "mappings": [
      {
        "backend": "${ref:gateway.router.backends[0].name}",
        "specification": "/oas/echo.yaml"
      }
    ],
    "order": 100
  }
}
